### ISSUE TITLE
AppImage doesn't seem to save options at all

### ISSUE THREAD

**Issue by Croydon** [gengjiawen/desktop#1]
On Fedora 25 the AppImage doesn't save GitHub Desktop options at all.

**Comment by gengjiawen** [comment]
I only pack the linux distro, but i am familar with the code.I may find some time to take a look, but I can't guarantee have a solution for this problem.

**Comment by gengjiawen** [comment]
Beside this problem, have run into other problem?

**Comment by probonopd** [comment]
Where does GitHub Desktop normally save its options? In `$HOME`?

**Comment by gengjiawen** [comment]
Seems like it's a bug. You can try this in the new 0.5.8 version. In 0.5.8 I have remove the js uglify. You can track error by opening develop tools in Menu `View -> Toggle develop tools`
```
Uncaught (in promise) Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:219:18)
    at /media/sf_Developer/webpack:/app/~/dugite/build/lib/git-process.js:45:1
    at Function.exec (/media/sf_Developer/webpack:/app/~/dugite/build/lib/git-process.js:28:1)
    at Q.measure (/media/sf_Developer/webpack:/app/src/lib/git/core.ts:110:30)
    at Object.<anonymous> (/media/sf_Developer/webpack:/app/src/ui/lib/git-perf.ts:19:10)
    at Generator.next (<anonymous>
```

**Comment by gengjiawen** [comment]
I have reported it to dugite: https://github.com/desktop/dugite-native/issues/46.

**Comment by gengjiawen** [comment]
I believe 0.6.1 fix this, please give a try https://github.com/gengjiawen/desktop/releases.

**Comment by Croydon** [comment]
@gengjiawen No, I didn't had other problems then this. Well, maybe with the exception that the app has no icon :)

Thank you :)
